name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Cache pipenv
      uses: actions/cache@v2
      id: cache-pipenv
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pipenv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install pipenv
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        python -m pip install pipenv
    - name: Install dependencies
      run: |
        make setup

    - name: Run checks [pylint, isort, black and pytest]
      run: |
        make check
